Fix: episode file url
CastosHQ/Seriously-Simple-Podcasting pull request #581
Opened 2020-12-22 21:05 UTC by barthc

Closes #573, and also fixes the file URL for all other instances of the media player.

The reason why version 2.4.2 works for inline media player is probably because of this  line https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/90d707577642790ae754fd3db865bba884b024ec/php/classes/controllers/class-frontend-controller.php#L438

2020-12-23 10:11 UTC, jonathanbossenger commented
@barthc is there any way you can update your forked version of the repository? The pull request contains commits all the way back to Nov 23, which makes it impossible to review just the work to be merged.

It can be done either via the GitHub UI - https://adrientorris.github.io/github/how-to-update-a-forked-repository-from-the-ui-on-github

Or via the command line - https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

2020-12-23 10:34 UTC, barthc commented
@jonathanbossenger  My fork is up to date. The issue here is that the PR is opened on the `develop` branch as suggested in the [contribution guide](https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/master/CONTRIBUTING.md). I just changed the base branch to `master`

2020-12-23 12:17 UTC, jonathanbossenger commented
@barthc Ah yes, my apologies, you are correct.

I've rebased `develop` and updated this back to be merged into `develop`, thanks.

2020-12-23 12:42 UTC, jonathanbossenger commented
@barthc thanks for the PR, looks good so far.

I do have one change request. While changing the meta audio_file field in the REST API is a solid solution, for the Castos importer, the audio_file field must remind the raw audio file URL.

In order to enable the player URL for the Castos Player block, instead of rewriting the audio_file field in the episodes route, I would prefer it if you added a new `player_link` REST API field in the same way that we the `download_link` field here: https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/77e714bb77061bafa1b0873d82c2d46fdf36d613/php/classes/rest/class-rest-api-controller.php#L75

That way it leaves the default data is as, meaning it has no effect on external services relying on the raw audio_file URL, but also allows us to use the correct URL in the player block.

Let me know if you have any questions about this.

2021-01-04 12:32 UTC, jonathanbossenger requested changes
Looks good so far, just one small change request. Thanks. Will test this out in the week.

2021-01-04 12:32 UTC, jonathanbossenger commented on php/classes/controllers/class-admin-controller.php
> +		$this->episode_controller = new Episode_Controller( $this->file, $this->version );
Is this episode_controller property on the admin_controller still needed?

2021-01-05 06:58 UTC, barthc commented on php/classes/controllers/class-admin-controller.php
> +		$this->episode_controller = new Episode_Controller( $this->file, $this->version );
Nope, it's not needed, I have removed it. Nice catch :+1:

2021-01-05 14:02 UTC, merged